# Generated by Django 5.0.6 on 2024-06-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('Name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=15)),
                ('Subject', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('FullName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=15)),
                ('Password', models.CharField(max_length=10)),
                ('GraduationYear', models.CharField(max_length=4)),
                ('PhoneNo', models.CharField(max_length=15)),
                ('desig', models.CharField(default='user', max_length=15)),
            ],
        ),
    ]
